name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file ./Api/pom.xml
  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
       - name: Cache local Maven repository
         uses: actions/cache@v2
         with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('./Api/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
       - name: Build package war
         run: mvn -B package -DskipTests --file ./Api/pom.xml
       - name: Upload .war
         uses: actions/upload-artifact@v2
         with:
          name: artifact
          path: ./Api/target/app.war
  deploy:
    needs: build
    name: Deploy on AWS Elastic Beanstall
    runs-on: ubuntu-latest
    steps:
      - name: Download war
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          wait_for_environment_recovery: 120
          application_name: app-spring-boot
          environment_name: Appspringboot-env
          version_label: latest-${{github.sha}}
          region: us-east-1
          deployment_package: app.war
